# Generated by Django 5.2.8 on 2025-11-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_elev', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('ora_inceput', models.TimeField()),
                ('ora_sfarsit', models.TimeField()),
                ('este_blocat', models.BooleanField(default=False)),
            ],
        ),
    ]
